# List of all configurations, overwritten sequentially; the basic configuration must always be first
configs:
  - configs/base.yaml #Always must be first!
  # setting 1 small data + good model
  # - configs/models/stacked_hourglass_pytorch.yaml
  # - configs/datasets/coco_dataset.yaml

  # setting 2 keypoint
  # - configs/models/test_pytorch.yaml
  # - configs/datasets/random_dataset_keypoints.yaml

  # setting 3 full dataset
  - configs/models/stacked_hourglass_pytorch.yaml
  # - configs/datasets/coco_dataset_full.yaml
  - configs/datasets/atlas_dataset.yaml

  # setting 4 random for testing
  # - configs/models/test_heatmaps_pytorch.yaml
  # - configs/datasets/random_dataset_heatmaps.yaml

  - configs/predicts/atlas_dataset.yaml
  